"""Deterministic rig planning from plain-language descriptions."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from rayflow.design.models import FixtureSlot, Position3D, Rig, Venue
from rayflow.engine.fixtures.library import FixtureLibrary

DEFAULT_FIXTURES = {
    "wash": {
        "fixture": "LED PAR 64 RGBW",
        "mode": "Default",
        "label": "PAR",
    },
    "pixel": {
        "fixture": "Robin iSpiiderX",
        "mode": "Mode 2 - Basic",
        "label": "Spiider",
    },
    "beam": {
        "fixture": "Robin MMX Blade",
        "mode": "Mode 1 - Standard",
        "label": "Blade",
    },
}

SCALE_DEFAULTS: dict[str, dict[str, Any]] = {
    "small": {
        "dimensions": (10.0, 6.0, 4.0),
        "counts": {"wash": 4, "pixel": 0, "beam": 0},
    },
    "medium": {
        "dimensions": (16.0, 9.0, 6.0),
        "counts": {"wash": 6, "pixel": 2, "beam": 2},
    },
    "large": {
        "dimensions": (24.0, 14.0, 9.0),
        "counts": {"wash": 8, "pixel": 4, "beam": 4},
    },
}


@dataclass(frozen=True)
class RigBuildPlan:
    """A proposed or applied generated RayFlow rig."""

    name: str
    description: str
    mode: str
    rig: Rig
    scale: str
    fixture_counts: dict[str, int]
    rationale: list[str]
    warnings: list[str] = field(default_factory=list)
    next_command: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "mode": self.mode,
            "scale": self.scale,
            "fixture_counts": dict(self.fixture_counts),
            "rationale": list(self.rationale),
            "warnings": list(self.warnings),
            "readiness": {
                "status": "ready" if not self.warnings else "warnings",
                "summary": _readiness_summary(self.warnings),
            },
            "rig": self.rig.as_dict(),
            "next_command": self.next_command,
        }


def plan_rig_build(
    name: str,
    description: str,
    *,
    overrides: dict[str, Any] | None = None,
    fixture_dir: str | Path = "data/fixtures/samples",
    apply: bool = False,
) -> RigBuildPlan:
    """Plan a deterministic rig from text plus optional structured overrides."""
    clean_description = description.strip()
    if not clean_description:
        raise ValueError("description must not be empty")

    overrides = overrides or {}
    warnings: list[str] = []
    rationale: list[str] = []
    scale = _infer_scale(clean_description, overrides)
    defaults = SCALE_DEFAULTS[scale]
    counts = dict(defaults["counts"])
    counts.update(_intent_count_adjustments(clean_description))
    counts.update(_override_counts(overrides))
    counts = {role: max(0, int(count)) for role, count in counts.items()}

    dimensions = _override_dimensions(overrides) or defaults["dimensions"]
    venue_name = str(overrides.get("venue_name") or f"{scale.title()} Generated Venue")

    fixture_specs = {role: dict(spec) for role, spec in DEFAULT_FIXTURES.items()}
    fixture_specs.update(_override_fixture_specs(overrides))
    _validate_fixture_specs(fixture_specs, fixture_dir, warnings)

    rationale.append(f"Inferred {scale} scale from description and overrides.")
    for role, count in counts.items():
        if count:
            rationale.append(f"Added {count} {role} fixture(s).")

    rig = Rig(
        name=name,
        venue=Venue(
            name=venue_name,
            dimensions=dimensions,
            notes="Generated by RayFlow rig builder.",
        ),
        fixtures=_build_slots(counts, fixture_specs, dimensions),
        notes=f"Generated from description: {clean_description}",
    )

    return RigBuildPlan(
        name=name,
        description=clean_description,
        mode="apply" if apply else "proposal",
        rig=rig,
        scale=scale,
        fixture_counts=counts,
        rationale=rationale,
        warnings=warnings,
        next_command=f'rayflow rig info "{name}" --json',
    )


def _infer_scale(description: str, overrides: dict[str, Any]) -> str:
    requested = str(overrides.get("scale", "")).strip().lower()
    if requested in SCALE_DEFAULTS:
        return requested
    text = description.lower()
    if any(word in text for word in ("large", "arena", "festival", "outdoor")):
        return "large"
    if any(word in text for word in ("medium", "theater", "theatre", "mid-size")):
        return "medium"
    return "small"


def _intent_count_adjustments(description: str) -> dict[str, int]:
    text = description.lower()
    adjustments: dict[str, int] = {}
    if any(word in text for word in ("beam", "gobo", "spot", "profile", "aerial")):
        adjustments["beam"] = max(2, adjustments.get("beam", 0))
    if any(word in text for word in ("pixel", "eye candy", "psychedelic", "movement")):
        adjustments["pixel"] = max(2, adjustments.get("pixel", 0))
    if any(word in text for word in ("front", "wash", "warm", "backlight")):
        adjustments["wash"] = max(4, adjustments.get("wash", 0))
    return adjustments


def _override_counts(overrides: dict[str, Any]) -> dict[str, int]:
    raw = overrides.get("fixture_counts", overrides.get("counts", {}))
    if not isinstance(raw, dict):
        raise ValueError("fixture_counts override must be an object")
    return {
        role: int(count)
        for role, count in raw.items()
        if role in DEFAULT_FIXTURES and count is not None
    }


def _override_dimensions(
    overrides: dict[str, Any],
) -> tuple[float, float, float] | None:
    raw = overrides.get("dimensions")
    if raw is None:
        return None
    if not isinstance(raw, list | tuple) or len(raw) != 3:
        raise ValueError("dimensions override must contain exactly 3 numbers")
    return (float(raw[0]), float(raw[1]), float(raw[2]))


def _override_fixture_specs(overrides: dict[str, Any]) -> dict[str, dict[str, str]]:
    raw = overrides.get("fixtures", {})
    if not isinstance(raw, dict):
        raise ValueError("fixtures override must be an object")
    result: dict[str, dict[str, str]] = {}
    for role, spec in raw.items():
        if role not in DEFAULT_FIXTURES:
            continue
        if not isinstance(spec, dict):
            raise ValueError(f"fixture spec for {role} must be an object")
        merged = dict(DEFAULT_FIXTURES[role])
        for key in ("fixture", "mode", "label"):
            if key in spec:
                merged[key] = str(spec[key])
        result[role] = merged
    return result


def _validate_fixture_specs(
    specs: dict[str, dict[str, str]],
    fixture_dir: str | Path,
    warnings: list[str],
) -> None:
    try:
        library = FixtureLibrary(fixture_dir)
        library.load()
    except (FileNotFoundError, ValueError) as exc:
        warnings.append(f"Fixture library could not be loaded: {exc}")
        return

    for role, spec in specs.items():
        parser = library.get(spec["fixture"])
        if parser is None:
            warnings.append(f"{role} fixture not found: {spec['fixture']}")
            continue
        if spec["mode"] not in parser.mode_names():
            warnings.append(
                f"{role} mode '{spec['mode']}' not found for {parser.name}; "
                f"available: {parser.mode_names()}"
            )


def _build_slots(
    counts: dict[str, int],
    specs: dict[str, dict[str, str]],
    dimensions: tuple[float, float, float],
) -> list[FixtureSlot]:
    slots: list[FixtureSlot] = []
    next_address = 1
    fixture_number = 1
    width, depth, height = dimensions
    for role in ("wash", "pixel", "beam"):
        count = counts.get(role, 0)
        spec = specs[role]
        for index in range(count):
            x = _spread_x(index, count, width)
            y = _role_y(role, depth)
            z = _role_z(role, height)
            slots.append(
                FixtureSlot(
                    fixture_name=spec["fixture"],
                    mode=spec["mode"],
                    label=f"{spec['label']} {index + 1}",
                    universe=0,
                    start_address=next_address,
                    position=Position3D(x=x, y=y, z=z, pan=0, tilt=0),
                    channels=str(fixture_number),
                )
            )
            next_address += 32
            fixture_number += 1
    return slots


def _spread_x(index: int, count: int, width: float) -> float:
    if count <= 1:
        return 0.0
    usable_width = width * 0.75
    left = -usable_width / 2
    return round(left + (usable_width / (count - 1)) * index, 2)


def _role_y(role: str, depth: float) -> float:
    if role == "wash":
        return round(depth * 0.2, 2)
    if role == "pixel":
        return round(depth * 0.65, 2)
    return round(depth * 0.85, 2)


def _role_z(role: str, height: float) -> float:
    if role == "wash":
        return round(height * 0.75, 2)
    return round(height * 0.9, 2)


def _readiness_summary(warnings: list[str]) -> str:
    if not warnings:
        return "Rig build plan is ready to apply."
    return f"Rig build plan produced {len(warnings)} warning(s)."
